apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: kube-public
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 718466725446.dkr.ecr.eu-west-1.amazonaws.com/bar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: db-connection
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"